#!/bin/zsh

MY_DIR="$(dirname "$(which "$0")")"
MY_PUBLIC="public"

DEBUG=false;

declare -A map

function log() {
    if [[ $DEBUG == true ]]; then
        echo $1;
    fi;
}

function read_key_values() {

    log "Reading key values for namespace $1"

    local namespace=$1
    if [[ -z $namespace ]]; then
        namespace="public"
    fi;

    local file="$MY_DIR/${namespace}_profile"
    local header_key="$namespace"

    if [[ -e $file ]]; then
        while read -r var value; do
            if [[ -z $value ]]; then
                log "Get key $var and empty"
                log "Save key $var for namespace root dir"
                map[$header_key]=$var
            else
                log "Get key $var and value $value"
                log "Save key : $namespace-$var => value : $value"
                map[$namespace-$var]="$value"
            fi
        done <$file
    fi
}

if [[ $1 == "-"* ]]; then
    namespace=${1:1}
    project=$2
else
    namespace=$MY_PUBLIC
    project=$1
fi

read_key_values
read_key_values $namespace;

if [[ $DEBUG == true ]]; then
    
    if [[ $SHELL == *"zsh"* ]]; then
        log "map:"
        for k in "${(@k)map}"; do
        log "$k => $map[$k]"
        done
    else
        log "map:"
        for key in "${map![@]}"; do
            log "$key => ${map[$key]}"
        done
    fi

fi

function get_dir() {

    local namespace=$1
    
    dir=$map[$namespace]
    if [[ -n $dir ]]; then
        dir=$dir/
    fi
    log "find dir $dir for namespace $namespace"
}

function get_final_path() {
    local namespace=$1
    local project=$2

    if [[ -n $project ]]; then
        local key="$namespace-$project";
        project_path=$map[$key]
    fi

    log "get final path $project_path for namespace $namespace and project $project"
}

get_dir $namespace
get_final_path $namespace $project

if [[ -z $project_path && $namespace != $MY_PUBLIC ]]; then
    get_dir $MY_PUBLIC
    get_final_path $MY_PUBLIC $project
fi

if [[ -z $project_path ]]; then
    get_dir $namespace
    project_path=$project
fi

if [[ -e $dir$project_path ]]; then
    cd $dir$project_path
else 
    echo "No suce directory $dir$project_path"
fi

unset map
unset dir
unset project_path
unset namespace
unset project